services:
  - type: web
    name: crm-connecting
    env: node
    plan: free
    region: oregon
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    startCommand: cd backend && node server-compatible.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: RENDER_NODE_VERSION
        value: 18.18.0
